version: 1.4.{build}.0
build_cloud: WIN-LKR467JS4GL
image: Windows
configuration: Release
skip_commits:
  files:
    - '**/*.md'
platform:
- x64
install:
- ps: Setup-VS2022
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
after_build:
- cmd: makecab.exe /f HidHide_%PLATFORM%.ddf
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\*.pdb'
- path: 'bin**\*.exe'
- path: 'disk1\*.cab'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true