version: 1.2.{build}.0
image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '**/*.md'
platform:
- x64
install:
- ps: iwr "https://download.microsoft.com/download/7/1/9/719a29d3-bf8c-49eb-b9bd-9bde8d17e142/wdk/wdksetup.exe" -OutFile wdksetup.exe
- cmd: .\wdksetup.exe /features + /q /norestart
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
after_build:
- cmd: makecab.exe /f HidHide_%PLATFORM%.ddf
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\*.pdb'
- path: 'bin**\*.exe'
- path: 'disk1\*.cab'
- path: 'bin**\*.msi'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true